version: "3.8"

services:
  
  frontend:
    image: nginx:latest
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/frontend/3Tierapplication/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  

volumes:
  mongo_data:

